# See https://starship.rs/config/#prompt
add_newline = true


# When capacity is over 30%, the battery indicator will not be displayed
[[battery.display]]  # "bold red" style and discharging_symbol when capacity is between 0% and 10%
threshold = 10
style = "bold red"

[[battery.display]]  # "bold yellow" style and 💦 symbol when capacity is between 10% and 30%
threshold = 30
style = "bold yellow"
discharging_symbol = "💦 "


# Replace the "❯" symbol in the prompt with "➜"
[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red) "


[directory]
read_only = " "
truncation_length = 3
truncation_symbol = "…/"


[env_var]
variable = "NODE_ENV"
format = "[$env_value] env($style)"


[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"

